### 1. 범주형 데이터

In [1]:
# 데이터 가져오기"
import pandas as pd
mydata = pd.read_csv('https://stats.idre.ucla.edu/stat/data/binary.csv')
mydata

admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

[400 rows x 4 columns]

In [2]:
# 데이터 분할
X = mydata.iloc[:, 1:]
y = mydata.iloc[:, 0]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)  # 평가데이터 25%

In [4]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [5]:
# nnet 적합
from sklearn.neural_network import MLPClassifier
clf2 = MLPClassifier(hidden_layer_sizes = 2, random_state = 1)
print(clf2.fit(X, y))
clf4 = MLPClassifier(hidden_layer_sizes = 4, random_state = 1)
print(clf4.fit(X, y))
clf6 = MLPClassifier(hidden_layer_sizes = 6, random_state = 1)
print(clf6.fit(X, y))
clf10 = MLPClassifier(hidden_layer_sizes = 10, random_state = 1)
print(clf10.fit(X, y))

MLPClassifier(hidden_layer_sizes=2, random_state=1)
MLPClassifier(hidden_layer_sizes=4, random_state=1)
MLPClassifier(hidden_layer_sizes=6, random_state=1)
MLPClassifier(hidden_layer_sizes=10, random_state=1)


In [6]:
print("clf2 학습 데이터 점수 : {}".format(clf2.score(X_train,y_train)))
print("clf2 평가 데이터 점수 : {}".format(clf2.score(X_test,y_test)))

from sklearn.metrics import accuracy_score
predict = clf2.predict(X_test)
print("clf2 정확도 : {}".format(accuracy_score(y_test,predict)))

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true = y_test, y_pred = predict)
print(confmat)

clf2 학습 데이터 점수 : 0.66
clf2 평가 데이터 점수 : 0.75
clf2 정확도 : 0.75
[[75  0]
 [25  0]]


In [7]:
print("clf4 학습 데이터 점수 : {}".format(clf4.score(X_train,y_train)))
print("clf4 평가 데이터 점수 : {}".format(clf4.score(X_test,y_test)))

from sklearn.metrics import accuracy_score
predict = clf4.predict(X_test)
print("clf4 정확도 : {}".format(accuracy_score(y_test,predict)))

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true = y_test, y_pred = predict)
print(confmat)

clf4 학습 데이터 점수 : 0.66
clf4 평가 데이터 점수 : 0.75
clf4 정확도 : 0.75
[[75  0]
 [25  0]]


In [8]:
print("clf6 학습 데이터 점수 : {}".format(clf6.score(X_train,y_train)))
print("clf6 평가 데이터 점수 : {}".format(clf6.score(X_test,y_test)))

from sklearn.metrics import accuracy_score
predict = clf6.predict(X_test)
print("clf6 정확도 : {}".format(accuracy_score(y_test,predict)))

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true = y_test, y_pred = predict)
print(confmat)

clf6 학습 데이터 점수 : 0.34
clf6 평가 데이터 점수 : 0.25
clf6 정확도 : 0.25
[[ 0 75]
 [ 0 25]]


In [9]:
print("clf10 학습 데이터 점수 : {}".format(clf10.score(X_train,y_train)))
print("clf10 평가 데이터 점수 : {}".format(clf10.score(X_test,y_test)))

from sklearn.metrics import accuracy_score
predict = clf10.predict(X_test)
print("clf10 정확도 : {}".format(accuracy_score(y_test,predict)))

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true = y_test, y_pred = predict)
print(confmat)

clf10 학습 데이터 점수 : 0.66
clf10 평가 데이터 점수 : 0.75
clf10 정확도 : 0.75
[[75  0]
 [25  0]]


### 2. 연속형 데이터

In [10]:
# 데이터 가져오기
import pandas as pd
regdata = pd.read_csv('https://stats.idre.ucla.edu/wp-content/uploads/2019/02/elemapi2v2.csv')
regdata

snum  dnum  api00  api99  growth  meals  ell  yr_rnd  mobility  acs_k3  \
1     906    41    693    600      93     67    9       0      11.0    16.0   
2     889    41    570    501      69     92   21       0      33.0    15.0   
3     887    41    546    472      74     97   29       0      36.0    17.0   
4     876    41    571    487      84     90   27       0      27.0    20.0   
5     888    41    478    425      53     89   30       0      44.0    18.0   
..    ...   ...    ...    ...     ...    ...  ...     ...       ...     ...   
396   482   796    745    736       9     27   12       0      11.0    18.0   
397   489   796    720    678      42     34    8       0      20.0    19.0   
398   504   796    802    787      15     26   10       0      21.0    19.0   
399   488   796    539    424     115     98   12       0      18.0    20.0   
400   479   796    512    447      65     98   34       0      31.0    19.0   

     ...  col_grad  grad_sch  avg_ed  full  emer  enroll  mealcat  collcat  \
1    ...         0         0     NaN    76    24     247        2        1   
2    ...         0         0     NaN    79    19     463        3        1   
3    ...         0         0     NaN    68    29     395        3        1   
4    ...         9         0    1.91    87    11     418        3        1   
5    ...         0         0    1.50    87    13     520        3        1   
..   ...       ...       ...     ...   ...   ...     ...      ...      ...   
396  ...        37         7    3.12    95     5     266        1        2   
397  ...        26         6    2.88    85     7     461        1        3   
398  ...        37        12    3.29    91     5     360        1        2   
399  ...         1         0    2.06    93     7     301        3        1   
400  ...         9         1    2.01    83     6     269        3        1   

     abv_hsg  lgenroll  
1        100  2.392697  
2        100  2.665581  
3        100  2.596597  
4         64  2.621176  
5         50  2.716003  
..       ...       ...  
396       95  2.424882  
397       92  2.663701  
398       97  2.556303  
399       90  2.478566  
400       69  2.429752  

[400 rows x 24 columns]

In [11]:
# 필요한 데이터 외에는 삭제
data = regdata.loc[:, ["api00", "enroll", "meals", "full"]]
data

api00  enroll  meals  full
1      693     247     67    76
2      570     463     92    79
3      546     395     97    68
4      571     418     90    87
5      478     520     89    87
..     ...     ...    ...   ...
396    745     266     27    95
397    720     461     34    85
398    802     360     26    91
399    539     301     98    93
400    512     269     98    83

[400 rows x 4 columns]

In [12]:
# 데이터 분할
X = data.iloc[:, 1:]
y = data.iloc[:, 0]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)  # 평가데이터 25%

In [14]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [15]:
# nnet 적합
from sklearn.neural_network import MLPClassifier
clf2 = MLPClassifier(hidden_layer_sizes = 2, random_state = 1)
print(clf2.fit(X, y))
clf4 = MLPClassifier(hidden_layer_sizes = 4, random_state = 1)
print(clf4.fit(X, y))
clf6 = MLPClassifier(hidden_layer_sizes = 6, random_state = 1)
print(clf6.fit(X, y))
clf10 = MLPClassifier(hidden_layer_sizes = 10, random_state = 1)
print(clf10.fit(X, y))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=2, random_state=1)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=4, random_state=1)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=6, random_state=1)
MLPClassifier(hidden_layer_sizes=10, random_state=1)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [16]:
# 예측 및 비교를 위한 역변환
pred2 = clf2.predict(X_test) * (max(data['api00']) - min(data['api00'])) + min(data['api00'])
pred4 = clf4.predict(X_test) * (max(data['api00']) - min(data['api00'])) + min(data['api00'])
pred6 = clf6.predict(X_test) * (max(data['api00']) - min(data['api00'])) + min(data['api00'])
pred10 = clf10.predict(X_test) * (max(data['api00']) - min(data['api00'])) + min(data['api00'])
actual = y_test * (max(data['api00']) - min(data['api00'])) + min(data['api00'])

In [17]:
# MAE
from sklearn.metrics import mean_absolute_error
print("clf2 MAE : {}".format(mean_absolute_error(y_test, pred2)))
print("clf4 MAE : {}".format(mean_absolute_error(y_test, pred4)))
print("clf6 MAE : {}".format(mean_absolute_error(y_test, pred6)))
print("clf10 MAE : {}".format(mean_absolute_error(y_test, pred10)))

clf2 MAE : 321931.99
clf4 MAE : 379877.07
clf6 MAE : 374875.11
clf10 MAE : 366178.78


In [18]:
# MSE
import numpy as np
from sklearn.metrics import mean_squared_error 
print("clf2 MSE : {}".format(mean_squared_error(y_test, pred2)))
print("clf4 MSE : {}".format(mean_squared_error(y_test, pred4)))
print("clf6 MSE : {}".format(mean_squared_error(y_test, pred6)))
print("clf10 MSE : {}".format(mean_squared_error(y_test, pred10)))

clf2 MSE : 106658215793.95
clf4 MSE : 145321737953.49
clf6 MSE : 140531368558.57
clf10 MSE : 140870276866.56


In [19]:
# RMSE
print("clf2 RMSE : {}".format(np.sqrt(mean_squared_error(y_test, pred2))))
print("clf4 RMSE : {}".format(np.sqrt(mean_squared_error(y_test, pred4))))
print("clf6 RMSE : {}".format(np.sqrt(mean_squared_error(y_test, pred6))))
print("clf10 RMSE : {}".format(np.sqrt(mean_squared_error(y_test, pred10))))

clf2 RMSE : 326585.69441105344
clf4 RMSE : 381210.8838339876
clf6 RMSE : 374875.13729049836
clf10 RMSE : 375326.89334306965
