## 8.2 커널 SVM

In [3]:
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from sklearn.datasets import make_circles
X, y = make_circles(n_samples = 100, noise = 0.1, factor = 0.1)
fig = go.Figure()
fig.add_trace(go.Scatter(x = X[ : , 0], y = X[ : , 1], mode = "markers", marker_color = y))
fig.update_layout(width = 600)
fig.show()

In [4]:
import numpy as np
r = np.exp(-(X ** 2).sum(1))
fig = go.Figure(data = go.Scatter3d(x = X[ : , 0], y = X[ : , 1],z = r, mode = "markers", marker_color = y))
fig.show()

## 8.3 Sklearn을 이용한 SVM
### 8.3.1 선형 SVM

In [5]:
import seaborn as sns
iris=sns.load_dataset('iris') 
X=iris.drop('species',axis=1) 
y=iris['species']
             
from sklearn.preprocessing import LabelEncoder 
classle=LabelEncoder()
y=classle.fit_transform(iris['species'].values)

from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=123, stratify=y)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

In [6]:
from sklearn.svm import SVC
svm = SVC(kernel = "linear", C = 1.0, random_state = 1)
svm.fit(X_train, y_train)
y_train_pred = svm.predict(X_train)
y_test_pred = svm.predict(X_test)

In [9]:
from sklearn import metrics
print(metrics.accuracy_score(y_train, y_train_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

0.9904761904761905
0.9777777777777777


In [10]:
metrics.confusion_matrix(y_test, y_test_pred)

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 15]])

In [12]:
print(metrics.classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



### 8.3.2 비선형 SVM(커널 SVM)

In [14]:
ksvm = SVC(kernel = "rbf", C = 1.0, gamma = 0.2, random_state = 42)
ksvm.fit(X_train_std, y_train)
y_train_pred = ksvm.predict(X_train_std)
y_test_pred = ksvm.predict(X_test_std)

In [16]:
from sklearn import metrics
print(metrics.accuracy_score(y_train, y_train_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

0.9904761904761905
0.9555555555555556


In [17]:
metrics.confusion_matrix(y_test, y_test_pred)

array([[15,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 15]])

In [18]:
print(svm.support_)

[ 21  43 101   8  23  33  38  42  54  58  76  82  85   5  10  19  27  41
  59  60  95]


In [19]:
print(svm.n_support_)

[ 3 10  8]
